### ISSUE TITLE
MySQL 3306/3307 disconnect between combine and combine-docker?

### ISSUE THREAD

**Issue by fruviad** [WSULib/combine-docker#38]
I'm not sure whether this would be a bug or something you guys haven't gotten to or ???

I'm running the "build.sh" installer on the latest master.  Progress reaches line 40 of build.sh and errors  occur, basically boiling down to:
```
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
```

It appears that the problem is due to the fact that MySQL port has been changed to 3307 in combine-docker, but it's still 3306 in combine, and that 3306 config is being copied into the django configuration.  I added code to the build.sh just before the failure point and swapped 3307 for 3306 in the combine/combine/combine/localsettings.py* files and that enabled the MySQL connection to work.

**Comment by antmoth** [comment]
We've updated v0.11 to use the 3307 port in localsettings.py.docker. It's just something we missed; sorry about that.
